spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.15
      database: doctor_service
      username:
      password:
server:
  port: 8200
logging:
  level:
#    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
#        web: WARN
        data:
            core:
              MongoTemplate: DEBUG
              MongoOperations: DEBUG
  pattern:
    console: "%msg%n"

